# Generated by Django 3.0.6 on 2020-12-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20201202_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
