# Generated by Django 3.0.6 on 2020-12-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20201202_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='good',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='read',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='readtext',
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
