# Generated by Django 3.0.6 on 2021-01-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_auto_20201217_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='files',
            field=models.FileField(blank=True, null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
